volumes:
  bitcoin-data:
  bitcoin-bin:

services:
  bitcoin-node:
    image: bitcoin-node
    build:
      context: .
      dockerfile: docker/bitcoin-node.dockerfile
    environment:
      BITCOIN_NETWORK: regtest
    ports:
      - "8332:8332"
      - "8333:8333"
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    privileged: true
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin
      - bitcoin-bin:/shared
      - /sys/kernel/debug:/sys/kernel/debug
    depends_on:
      nats:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/peer-observer/scripts/bitcoin-node-healthcheck.sh"]
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 5s

  nats:
    image: nats:2
    build:
      context: .
      dockerfile: docker/nats.dockerfile
    ports:
      - "4222:4222"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8222/healthz"]
      interval: 1m
      timeout: 1s
      retries: 3
      start_period: 1s
