services:
  logger:
    image: peer-observer-tools
    build:
      context: ../
      dockerfile: docker/peer-observer-tools.dockerfile
    command:
      ["/home/appuser/logger", "--nats-address", "nats://nats:4222"]
    depends_on:
      nats:
        condition: service_healthy
    profiles: [monitoring, logger]
